name = "Tk"
uuid = "4225ea8a-3324-57e7-9ddc-5798a2cb9eab"
version = "0.8.0"

[deps]
Base64 = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"
Cairo = "159f3aea-2a34-519c-b102-8c37f9878175"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Tcl_jll = "9fc9b8dd-f768-5d0d-bb0b-e65961e00eb6"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Tk_jll = "056b5f69-f28f-5060-ad8a-df43647a2b5c"

[compat]
Cairo = "1"
Tcl_jll = "9"
Tk_jll = "9"
julia = "1.6"
